myData = [
    {
        "repo": "kafka",
        "title": "[DPE-9107] feat: add machines support to TF module@@@https://github.com/canonical/kafka-operator/pull/463",
        "created": "2026-01-27 11:00:44 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "docs: Add autogenerated metadata description@@@https://github.com/canonical/kafka-operator/pull/462",
        "created": "2026-01-25 12:59:29 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: Discourse link fix for v3@@@https://github.com/canonical/kafka-operator/pull/461",
        "created": "2026-01-25 00:58:11 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: Fix the discourse link@@@https://github.com/canonical/kafka-operator/pull/460",
        "created": "2026-01-25 00:50:27 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: Add GA and cookie consent@@@https://github.com/canonical/kafka-operator/pull/459",
        "created": "2026-01-23 15:14:33 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: Update baseurl for sitemaps to work correctly@@@https://github.com/canonical/kafka-operator/pull/456",
        "created": "2026-01-15 21:12:44 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: Update baseurl for sitemaps to work correctly@@@https://github.com/canonical/kafka-operator/pull/455",
        "created": "2026-01-15 20:48:23 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: v.4 Tutorial fixes after testing@@@https://github.com/canonical/kafka-operator/pull/454",
        "created": "2026-01-15 17:26:08 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "docs: [Experimental] Markdown formatter@@@https://github.com/canonical/kafka-operator/pull/452",
        "created": "2026-01-12 12:58:13 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "test: Juju 4@@@https://github.com/canonical/kafka-operator/pull/451",
        "created": "2026-01-12 07:29:11 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "refactor: remove libjuju, pytest-operator dep.@@@https://github.com/canonical/kafka-operator/pull/449",
        "created": "2026-01-09 09:17:54 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "docs: [Experimental] Ulwazi theme preview@@@https://github.com/canonical/kafka-operator/pull/444",
        "created": "2025-12-15 14:26:12 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "[DPE-9030] feat: add roles-mapping config option@@@https://github.com/canonical/kafka-operator/pull/441",
        "created": "2025-12-10 12:16:21 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "[DPE-8940] add OAuth integration tests and docs@@@https://github.com/canonical/kafka-operator/pull/439",
        "created": "2025-11-28 07:21:05 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "[DPE-8698] 4.x Config to switch cluster to DNS@@@https://github.com/canonical/kafka-operator/pull/436",
        "created": "2025-11-19 14:01:33 ",
        "user": "zmraul"
    },
    {
        "repo": "kafka",
        "title": "[DPE-8849] docs: add how-to guide for Kafka UI@@@https://github.com/canonical/kafka-operator/pull/433",
        "created": "2025-11-13 11:07:51 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "chore: Add a pull request template with a checklist@@@https://github.com/canonical/kafka-operator/pull/417",
        "created": "2025-09-26 18:12:55 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka",
        "title": "[DPE-7843] refactor: rename broker to kafka@@@https://github.com/canonical/kafka-operator/pull/404",
        "created": "2025-08-25 07:49:49 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka",
        "title": "[POC] Tracing@@@https://github.com/canonical/kafka-operator/pull/266",
        "created": "2024-10-28 15:37:43 ",
        "user": "zmraul"
    },
    {
        "repo": "kafka-k8s",
        "title": "docs: Add autogenerated metadata description@@@https://github.com/canonical/kafka-k8s-operator/pull/247",
        "created": "2026-01-26 14:26:39 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka-k8s",
        "title": "Update baseurl for sitemaps to work correctly@@@https://github.com/canonical/kafka-k8s-operator/pull/246",
        "created": "2026-01-15 21:19:50 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka-k8s",
        "title": "Update baseurl for sitemaps to work correctly@@@https://github.com/canonical/kafka-k8s-operator/pull/245",
        "created": "2026-01-15 20:50:32 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka-k8s",
        "title": "[DPE-8850] docs: add Kafka UI how-to@@@https://github.com/canonical/kafka-k8s-operator/pull/242",
        "created": "2026-01-07 07:21:03 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-k8s",
        "title": "ci: stabilize network cut test@@@https://github.com/canonical/kafka-k8s-operator/pull/239",
        "created": "2025-12-08 12:43:54 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-k8s",
        "title": " [DPE-9032] chore: use non-root user@@@https://github.com/canonical/kafka-k8s-operator/pull/238",
        "created": "2025-12-08 05:31:09 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-k8s",
        "title": "[DPE-8698] 3.x Config to switch cluster to DNS@@@https://github.com/canonical/kafka-k8s-operator/pull/237",
        "created": "2025-12-04 09:59:10 ",
        "user": "zmraul"
    },
    {
        "repo": "kafka-k8s",
        "title": "chore: Add a pull request template with a checklist@@@https://github.com/canonical/kafka-k8s-operator/pull/222",
        "created": "2025-09-26 18:31:14 ",
        "user": "izmalk"
    },
    {
        "repo": "kafka-k8s",
        "title": "Add TIOBE to CI@@@https://github.com/canonical/kafka-k8s-operator/pull/181",
        "created": "2025-04-03 18:34:23 ",
        "user": "phvalguima"
    },
    {
        "repo": "karapace",
        "title": "[DPE-9107] feat: add machines support to TF module@@@https://github.com/canonical/karapace-operator/pull/48",
        "created": "2026-01-29 06:10:10 ",
        "user": "imanenami"
    },
    {
        "repo": "karapace-k8s",
        "title": "ci: remove lib-check@@@https://github.com/canonical/karapace-k8s-operator/pull/28",
        "created": "2025-12-08 07:22:47 ",
        "user": "imanenami"
    },
    {
        "repo": "karapace-k8s",
        "title": "[DPE-8614] Enable Rest TLS@@@https://github.com/canonical/karapace-k8s-operator/pull/27",
        "created": "2025-11-07 16:33:26 ",
        "user": "zmraul"
    },
    {
        "repo": "karapace-k8s",
        "title": "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows@@@https://github.com/canonical/karapace-k8s-operator/pull/12",
        "created": "2024-09-03 22:53:42 ",
        "user": "dependabot[bot]"
    },
    {
        "repo": "karapace-k8s",
        "title": "Bump cryptography from 39.0.2 to 43.0.1@@@https://github.com/canonical/karapace-k8s-operator/pull/11",
        "created": "2024-09-03 22:53:33 ",
        "user": "dependabot[bot]"
    },
    {
        "repo": "karapace-k8s",
        "title": "Bump ops from 2.14.0 to 2.15.0@@@https://github.com/canonical/karapace-k8s-operator/pull/7",
        "created": "2024-07-22 17:42:09 ",
        "user": "dependabot[bot]"
    },
    {
        "repo": "karapace-k8s",
        "title": "Bump black from 22.12.0 to 24.3.0@@@https://github.com/canonical/karapace-k8s-operator/pull/6",
        "created": "2024-07-22 12:27:00 ",
        "user": "dependabot[bot]"
    },
    {
        "repo": "karapace-k8s",
        "title": "Bump certifi from 2024.6.2 to 2024.7.4@@@https://github.com/canonical/karapace-k8s-operator/pull/4",
        "created": "2024-07-22 12:26:54 ",
        "user": "dependabot[bot]"
    },
    {
        "repo": "kafka-connect",
        "title": "[DPE-9107] feat: add machines support to TF module@@@https://github.com/canonical/kafka-connect-operator/pull/47",
        "created": "2026-01-28 06:33:37 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-connect",
        "title": "[DPE-6499][DO NOT MERGE] - feat: COS integration tests for Kafka Connect charm@@@https://github.com/canonical/kafka-connect-operator/pull/13",
        "created": "2025-02-21 14:52:23 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-connect-k8s",
        "title": "fix: use charmed-dba role for mysql@@@https://github.com/canonical/kafka-connect-k8s-operator/pull/19",
        "created": "2026-01-26 07:23:11 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-connect-k8s",
        "title": "Configure Renovate@@@https://github.com/canonical/kafka-connect-k8s-operator/pull/2",
        "created": "2025-03-18 06:16:51 ",
        "user": "renovate[bot]"
    },
    {
        "repo": "kafka-ui",
        "title": "[DPE-9107] feat: add machines support to TF module@@@https://github.com/canonical/kafka-ui-operator/pull/13",
        "created": "2026-01-29 06:14:36 ",
        "user": "imanenami"
    },
    {
        "repo": "kafka-ui",
        "title": "[DO NOT MERGE] ci: test latest lxd image@@@https://github.com/canonical/kafka-ui-operator/pull/12",
        "created": "2026-01-07 15:05:39 ",
        "user": "imanenami"
    },
    {
        "repo": "zookeeper",
        "title": "Add request_checksum_calculation and response_checksum_validation as S3 config arguments@@@https://github.com/canonical/zookeeper-operator/pull/201",
        "created": "2025-11-26 07:49:07 ",
        "user": "ggouzi"
    },
    {
        "repo": "zookeeper",
        "title": "Add TIOBE to CI@@@https://github.com/canonical/zookeeper-operator/pull/194",
        "created": "2025-04-03 18:38:13 ",
        "user": "phvalguima"
    },
    {
        "repo": "zookeeper",
        "title": "tests: get the relation from the output state@@@https://github.com/canonical/zookeeper-operator/pull/191",
        "created": "2025-03-27 09:00:23 ",
        "user": "tonyandrewmeyer"
    },
    {
        "repo": "zookeeper",
        "title": "[DPE-5626] chore: update ZooKeeper `up` alerting@@@https://github.com/canonical/zookeeper-operator/pull/166",
        "created": "2024-10-08 01:59:39 ",
        "user": "marcoppenheimer"
    },
    {
        "repo": "zookeeper-k8s",
        "title": "[DPE-8993] chore: partial sync with VM@@@https://github.com/canonical/zookeeper-k8s-operator/pull/140",
        "created": "2025-12-01 10:58:27 ",
        "user": "zmraul"
    },
    {
        "repo": "zookeeper-k8s",
        "title": "Add optional flags to provides endpoints@@@https://github.com/canonical/zookeeper-k8s-operator/pull/136",
        "created": "2025-06-26 18:36:35 ",
        "user": "rpbritton"
    },
    {
        "repo": "zookeeper-k8s",
        "title": "Add TIOBE to CI@@@https://github.com/canonical/zookeeper-k8s-operator/pull/132",
        "created": "2025-04-03 18:36:39 ",
        "user": "phvalguima"
    }
]